"""
ProofMatch AI — Tool 6: Image Metadata analyzer
Extracts EXIF and format metadata from the uploaded image to detect editing software signatures.
"""

import logging
import base64
import io
from PIL import Image, ExifTags

logger = logging.getLogger("proofmatch.tools.metadata")

# Known legitimate camera/screenshot makers vs known editing software
KNOWN_EDITORS = ["Adobe Photoshop", "Canva", "GIMP", "Affinity", "Pixelmator", "Corel"]


async def analyze_image_metadata(image_base64: str) -> dict:
    """
    Extract EXIF data and analyze it for signs of image manipulation software.

    Args:
        image_base64: Base64-encoded image data

    Returns:
        Dictionary with metadata properties and potential editing flags.
    """
    logger.info("Starting image metadata analysis")
    
    result = {
        "has_exif": False,
        "format": "Unknown",
        "dimensions": None,
        "software": None,
        "is_edited": False,
        "metadata_summary": "No metadata found",
        "flags": []
    }

    try:
        image_bytes = base64.b64decode(image_base64)
        image = Image.open(io.BytesIO(image_bytes))
        
        result["format"] = image.format
        result["dimensions"] = f"{image.width}x{image.height}"
        
        exif_data = image.getexif()
        
        if not exif_data:
            result["metadata_summary"] = f"{image.format} image ({image.width}x{image.height}) stripped of EXIF data. This is common for WhatsApp/Telegram forwards, but reduces traceability."
            # Not explicitly flagging missing EXIF as an error, just an observation.
            return result
        
        result["has_exif"] = True
        extracted_exif = {}
        
        # Decode EXIF
        for tag_id, value in exif_data.items():
            tag = ExifTags.TAGS.get(tag_id, tag_id)
            if isinstance(value, bytes):
                try:
                    value = value.decode("utf-8").strip("\x00")
                except Exception:
                    continue
            extracted_exif[str(tag)] = str(value)

        # Check for Software tags
        software = extracted_exif.get("Software", "") or extracted_exif.get("ProcessingSoftware", "")
        if software:
            result["software"] = software
            # Check if software matches known editors
            is_editor = any(editor.lower() in software.lower() for editor in KNOWN_EDITORS)
            if is_editor:
                result["is_edited"] = True
                result["flags"].append(f"Image was saved using editing software: {software}")
                result["metadata_summary"] = f"CRITICAL: EXIF data indicates manipulation by {software}."
            else:
                result["metadata_summary"] = f"Image generated by {software}. No known editing signatures found."
        else:
            result["metadata_summary"] = "EXIF intact but no 'Software' tag present."

        return result

    except Exception as e:
        logger.error(f"Metadata extraction failed: {e}")
        result["metadata_summary"] = f"Failed to extract metadata: {str(e)}"
        return result
